name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получить код из репозитория
      - uses: actions/checkout@v4

      # Шаг 2: Установить Java
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # Шаг 3: Дать права на выполнение gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
 # Шаг 4: Собрать проект, запустить приложение и выполнить тесты
      - name: Build, start app and run tests
        run: |

          # Запускаем приложение в фоновом режиме
          java -jar app/build/libs/app-deadline.jar &

          # Запускаем тесты в headless режиме
          ./gradlew test -Dselenide.headless=true
      
